### ISSUE TITLE
Make a dummy language pack containing reversed/accented strings.

### ISSUE THREAD

**Issue by arceduardvincent** [fle-internal/ka-lite-central#229]
Branch: develop

Expected Behaviour:
>1. The `dummy language pack` will replicate the translation string as dummy translation for test and developement.
> 2. The `.po` files were the sets of translation string that will converted to our `.mo` files.

Current Behaviour:
>1. We don't have any means to test if the translation is propagate especially when the crowdin strings are not yet approved.
>2. We  can't test if the translation works along with the designated string that intended to it.

**Comment by arceduardvincent** [comment]
This issue will comply the `dummy language packs` requested for the test as per requested by @jamalex in https://github.com/learningequality/ka-lite/issues/3075

**Comment by rtibbles** [comment]
:+1:

**Comment by cpauya** [comment]
The [update_pot](https://github.com/fle-internal/ka-lite-central/blob/master/centralserver/i18n/management/commands/update_pot.py#L8) management command mentions 

> It has an optional flag, -t, which inserts asterisks around the strings in the po files, and
compiles them, so that when you run the server, English has been translated to *English* in the
hope of making it easy to identify unwrapped strings.

So whoever works on this issue can verify if that works and should be helpful to fix this issue.

**Comment by cpauya** [comment]
As per @jamalex:
> See here for how edX does it: https://github.com/edx/i18n-tools/blob/master/i18n/dummy.py

**Comment by aronasorman** [comment]
Solved in https://github.com/learningequality/ka-lite/issues/3323
